# codemagic.yaml
workflows:
  nextjs-app:
    name: Daily Dish Next.js App
    instance_type: linux_x2
    max_build_duration: 10
    environment:
      node: '20' # Specify your Node.js version
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build Next.js application
        script: |
          npm run build
    artifacts:
      - .next/**/*
      - public/**/*
      - next.config.ts
      - package.json
      - apphosting.yaml
    publishing:
      # You can configure publishing to Firebase, GitHub Releases, etc. here
      # See Codemagic docs for more info: https://docs.codemagic.io/publishing/
      # Example for Firebase App Hosting:
      # firebase:
      #   project: your-firebase-project-id
      #   token: $FIREBASE_TOKEN # Stored as a secure environment variable in Codemagic
      #   site_name: your-app-hosting-site-name
      email:
        recipients:
          - user@example.com # Add your email here
        notify:
          success: true
          failure: true

